version: '3'

services:
  app:
    build: ./api
    command: ./chat_back
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
  db:
    image: postgres:latest
    container_name: postgres_db_${APP_NAME}
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_store:/var/lib/postgresql/data
  db-dev:
    image: postgres:latest
    container_name: postgres_db_${APP_NAME}_dev
    hostname: ${POSTGRES_HOSTNAME}_dev
    ports:
      - "${POSTGRES_PORT_DEV}:5432"
    volumes:
      - db_store_dev:/var/lib/postgresql/data
  migrate:
    build: ./migration
    container_name: migrate_${APP_NAME}
    volumes:
      - ./db:/db:ro
    entrypoint: ["/bin/bash", "/app/wait-for-it.sh", "${POSTGRES_HOSTNAME}:5432", "--",
      "atlas", "schema", "apply",
      "--url", "${POSTGRES_URL}",
      "--dev-url", "${POSTGRES_URL_DEV}",
      "--to", "file:///db/schema.sql",
      "--auto-approve"
    ]
    depends_on:
      - db
      - db-dev

volumes:
  db_store:
  db_store_dev: